version: '2'
services:
  mongo:
    image: mongo
    volumes:
      - ./mongo/data:/data/db
    ports:
      - "27017:27017"
  server:
    build: ./server
    volumes:
      - ./server:/server
      - /server/node_modules
    ports:
      - "8080:8080"
    links:
      - mongo
  client:
    build: ./client
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "3000:3000"
